#!/bin/bash

# Update package list and install git and wget
sudo apt update
sudo apt install -y git wget

# Clone the Nusantara repository
git clone https://github.com/sguresearcher/nusantara.git

# Pull all required Docker images
docker pull ghcr.io/dfir-iris/iriswebapp_db:v2.4.19
docker pull ghcr.io/dfir-iris/iriswebapp_app:v2.4.19
docker pull ghcr.io/dfir-iris/iriswebapp_nginx:v2.4.19
docker pull rabbitmq:3-management-alpine
docker pull iriswebapp_db:v2.4.7
docker pull iriswebapp_app:v2.4.7
docker pull iriswebapp_nginx:v2.4.7
docker pull ixdotai/smtp
docker pull valkey/valkey:7.2
docker pull mariadb:10.11
docker pull ghcr.io/misp/misp-docker/misp-core:v2.4.197
docker pull ghcr.io/misp/misp-docker/misp-modules:v2.4.197
docker pull ghcr.io/shuffle/shuffle-frontend:1.4.2
docker pull ghcr.io/shuffle/shuffle-backend:1.4.2
docker pull ghcr.io/shuffle/shuffle-orborus:1.4.0
docker pull opensearchproject/opensearch:2.14.0
docker pull wazuh/wazuh-manager:4.9.2
docker pull wazuh/wazuh-indexer:4.9.2
docker pull wazuh/wazuh-dashboard:4.9.2
